server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
  instance:
    hostname: employee-service
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: br.com.eljc

spring:
  output:
    ansi:
      enabled: always