version: "3.7"
services:
  config-service:
    image: elderjc/config-service:0.0.1-SNAPSHOT
    ports:
      - "8088:8088"
  discovery-service:
    image: elderjc/discovery-service:0.0.1-SNAPSHOT
    ports:
      - "8061:8061"
    depends_on:
      - config-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  employee-service:
    image: elderjc/employee-service:0.0.1-SNAPSHOT
    ports:
      - "8081"
    depends_on:
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  department-service:
    image: elderjc/department-service:0.0.1-SNAPSHOT
    ports:
      - "8082"
    depends_on:
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway-service:
    image: elderjc/gateway-service:0.0.1-SNAPSHOT
    ports:
      - "8060:8060"
    depends_on:
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker